version: '2'
services:
  chrome:
    image: selenium/node-chromium:127.0-chromedriver-127.0-grid-4.23.1-20240820
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=5
      - SE_START_XVFB=false
      - SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP=true
    ports:
      - "6900:5900"

  selenium-hub:
    image: selenium/hub:4.23.1-20240820
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
